FE = input("Enter Foundation English Score : ")
GB = input("Enter General Business Score : ")
ITCS = input("Enter Introduction to Computer Systems Score : ")
CP = input("Enter Computer Programming Score : ")
print("--- Your Score ---")
print("Foundation English : " + FE)
print("General Business : " + GB)
print("Introduction to Computer Systems : " + ITCS)
print("Computer Programming : " + CP)